- template/src/lib/sdk/widgets/CategoryWidget.js
- template/src/lib/sdk/widgets/FormulaWidget.js
It depends on https://github.com/CartoDB/airship/pull/727
> Activate loading state for widgets

- template/package.dev.json
- template/src/components/views/stores/Stores.js
- template/src/components/views/stores/StoresDetail.js
- template/src/components/views/stores/common.js
- template/src/components/views/stores/constants.js
This PR requires HistogramWidgetUI: https://github.com/CartoDB/airship/pull/728
> using histogram in storeDetails

- template/src/components/views/Home.js
- template/src/components/views/stores/StoresDetail.js
Related to https://app.clubhouse.io/cartoteam/story/117199/fix-home-styles
> Styling cleaning [ch117199]

- template/src/components/views/stores/StoresDetail.js
- template/src/models/StoreModel.js
Related to https://app.clubhouse.io/cartoteam/story/116017/changes-to-store
> feat: Remove nearest stores [ch116017]

- template/src/components/layers/StoresLayer.js
- template/src/components/views/datasets/UserDatasets.js
- template/src/components/views/stores/Stores.js
- template/src/components/views/stores/StoresDetail.js
- template/src/components/views/stores/StoresList.js
- template/src/lib/sdk/widgets/FormulaWidget.js
- template/src/routes.js
Related to https://app.clubhouse.io/cartoteam/story/116017/changes-to-store
> feat: Refactor Stores section to keep state between subsections [ch116017]

- template/src/components/views/Home.js
- template/src/components/views/stores/StoresDetail.js
Related to https://app.clubhouse.io/cartoteam/story/116529/loading
> feat: Add loading spinner for Stores Detail [ch116529]

- template/src/components/common/Map.js
- template/src/components/views/Home.js
- template/src/config/cartoSlice.js
- template/src/lib/sdk/google/GoogleMap.js
- template/src/lib/sdk/utils/debounce.js
I've just upload some fixes for GoogleMap, and a minor refactor for Map.js
Also I've fixed a minor error in debounce. with anonymous function, arguments were args from parent.
> Refactor and fixes for Map and GMaps

- template/docs/README.md
- template/src/components/layers/KpiLayer.js
- template/src/components/layers/StoresLayer.js
- template/src/components/views/Kpi.js
- template/src/components/views/stores/Stores.js
- template/src/components/views/stores/StoresDetail.js
- template/src/components/views/stores/StoresList.js
- template/src/config/cartoSlice.js
- template/src/lib/sdk/models/CategoryModel.js
- template/src/lib/sdk/models/FilterConditionBuilder.js
- template/src/lib/sdk/models/FilterQueryBuilder.js
- template/src/lib/sdk/models/FormulaModel.js
- template/src/lib/sdk/models/HistogramModel.js
- template/src/lib/sdk/models/index.js
- template/src/lib/sdk/widgets/CategoryWidget.js
- template/src/lib/sdk/widgets/HistogramWidget.js
- template/src/lib/sdk/widgets/index.js
- template/src/models/StoreModel.js
> Histogram with filters

- template/src/lib/sdk/widgets/FormulaWidget.js
- template/src/lib/ui/utils/animateValue.js
- template/src/lib/ui/widgets/FormulaWidgetUI.js
Story details: https://app.clubhouse.io/cartoteam/story/116523
> Animate formula widget value [ch116523]

- template/src/components/layers/StoresLayer.js
- template/src/lib/sdk/models/HistogramModel.js
- template/src/lib/ui/widgets/HistogramWidgetUI.js
Remove params, no longer used because has been removed in #73
> Remove useless code

- template/src/lib/ui/stories/widgets/CategoryWidgetUI.stories.js
- template/src/lib/ui/theme/carto-theme.js
- template/src/lib/ui/widgets/CategoryWidgetUI.js
- template/src/lib/widgets/CategoryWidget.js
- template/src/lib/widgets/models/CategoryModel.js
Story details: https://app.clubhouse.io/cartoteam/story/116517
> Category widget

- template/src/components/views/datasets/Datasets.js
- template/src/components/views/datasets/UserDatasets.js
- template/src/lib/ui/theme/carto-theme.js
Story details: https://app.clubhouse.io/cartoteam/story/120005
> fix: datasets list styles

- template/src/components/views/datasets/Datasets.js
- template/src/components/views/datasets/UserDatasets.js
- template/src/lib/ui/theme/carto-theme.js
Related to https://app.clubhouse.io/cartoteam/story/120005/datasets-styles-broken
> Make all datasets list item clickable [ch120005]

- hygen/_templates/layer/new/layer.ejs.t
- template-sample-app/template/src/components/layers/OAuthLayer.js
- template-sample-app/template/src/utils/htmlForFeature.js
- template-skeleton/template/src/utils/htmlForFeature.js
Story details: https://app.clubhouse.io/cartoteam/story/120466
> Enable hover at layer generator

- CHANGELOG.md
- template-sample-app/template.json
- template-sample-app/template/.env
- template-sample-app/template/package.dev.json
- template-skeleton/template.json
- template-skeleton/template/.env
- template-skeleton/template/package.dev.json
Some patches to be included in the next release:
- https with .env (tested locally)
- update carto-react reference
- CHANGELOG
> Fix https + changelog + lib update

- CHANGELOG.md
- template-sample-app/template/src/components/views/stores/Stores.js
- template-sample-app/template/src/components/views/stores/StoresDetail.js
Story details: https://app.clubhouse.io/cartoteam/story/120578
> Mark the current store as selected

- CHANGELOG.md
- template-sample-app/template/src/components/common/Header.js
- template-sample-app/template/src/components/views/datasets/UserDatasets.js
- template-sample-app/template/src/components/views/login/UserMenu.js
- template-sample-app/template/src/components/views/login/UserMenuLogin.js
- template-skeleton/template/src/components/common/Header.js
- template-skeleton/template/src/components/views/login/UserMenu.js
- template-skeleton/template/src/components/views/login/UserMenuLogin.js
Related to https://github.com/CartoDB/carto-react-lib/pull/44
This allows more flexibility (eg. custom styling in the app)
> refactor: local UserMenuLogin to manage Login button

- template-sample-app/template/src/components/common/Header.js
- template-sample-app/template/src/components/views/Kpi.js
- template-sample-app/template/src/components/views/Main.js
- template-sample-app/template/src/components/views/datasets/Datasets.js
- template-sample-app/template/src/components/views/datasets/UserDatasets.js
- template-sample-app/template/src/components/views/stores/StoresDetail.js
- template-sample-app/template/src/components/views/stores/StoresList.js
- template-skeleton/template/src/components/common/Header.js
- template-skeleton/template/src/components/views/Main.js
Related to https://app.clubhouse.io/cartoteam/story/123327/qa-design-mobile
> Mobile design fixes

- template-sample-app/template/src/components/common/Map.js
- template-sample-app/template/src/components/common/ZoomControl.js
- template-sample-app/template/src/components/views/Main.js
- template-sample-app/template/src/components/views/datasets/UserDatasets.js
- template-skeleton/template/src/components/common/Map.js
- template-skeleton/template/src/components/common/ZoomControl.js
- template-skeleton/template/src/components/views/Main.js
Related to https://app.clubhouse.io/cartoteam/story/120489/qa-design-issues
> Design fixes

- template-sample-app/template/src/data/sources/kpiSource.js
- template-sample-app/template/src/data/sources/storesSource.js
For proper client-side calculations on widgets
> fix: SQL sources require cartodb_id 

- template-sample-app/template/cypress/integration/config.js
- template-sample-app/template/cypress/integration/tileset_page_spec.js
Add basic e2e tests for Tileset page.
> Add e2e tests for Tileset page

- CHANGELOG.md
- template-sample-app/template/src/components/common/Isochrone.js
Clean isochrone if user logouts.
For: https://app.clubhouse.io/cartoteam/story/132669/qa-clean-isochrone-if-user-logouts
> feat: clean isochrone if user logouts

- CHANGELOG.md
- template-sample-app/package.json
- template-sample-app/template.json
- template-sample-app/template/config-overrides.js
- template-sample-app/template/package.dev.json
- template-skeleton/package.json
- template-skeleton/template.json
- template-skeleton/template/config-overrides.js
- template-skeleton/template/package.dev.json
- template-skeleton/template/src/config/store.js
Update the carto-react-lib to latest, so we can fix the luma mismatch
> Release beta 12

- CHANGELOG.md
- hygen/_templates/layer/new/prompt.js
Error: "my source is specified as type: 'sql' but I get `The source has an unknown type error` when trying to create a layer from hygen
> Fix layer hygen unable to identify proper sources 

- CHANGELOG.md
- template-sample-app/template/src/assets/markers/geocoder-marker.svg
- template-sample-app/template/src/components/layers/GeocoderLayer.js
- template-sample-app/template/src/utils/svgToDataUrl.js
- template-skeleton/template/src/assets/markers/geocoder-marker.svg
Geocoder marker was not correctly rendered in iOS devices.
> fix: cross browser geocoder marker display

- CHANGELOG.md
- template-skeleton/template/src/utils/htmlForFeature.js
For: https://app.clubhouse.io/cartoteam/story/141677/htmlforfeature-not-updated-in-skeleton
> fix: update htmlForFeature in skeleton

- CHANGELOG.md
- template-sample-app/template/public/index.html
- template-skeleton/template/public/index.html
Workaround to fix a react warning on chrome
> fix: react warning

- CHANGELOG.md
- template-sample-app/template/package.dev.json
- template-sample-app/template/src/components/views/Kpi.js
- template-skeleton/template/package.dev.json
For: https://app.clubhouse.io/cartoteam/story/143646/linter-fix-on-templates
> fix: make prettier dynamic when running lint:fix

- CHANGELOG.md
- template-sample-app/template/package.dev.json
- template-skeleton/template/package.dev.json
Update hygen to latest version, to fix certain issues on Windows users
For: https://app.clubhouse.io/cartoteam/story/150879/error-with-code-generator-in-windows
> Fix hygen not working properly on Windows

- template-sample-app/template/cypress.json
- template-sample-app/template/src/store/initialStateSlice.js
For: https://app.clubhouse.io/cartoteam/story/155287/adapt-tests
> Adapt e2e tests for carto-cloud-native

- DEVELOPERS.md
- README.md
- template-base-2/template/README.md
- template-base-3-typescript/template/README.md
- template-base-3/template/README.md
- template-sample-app-2/template/README.md
- template-sample-app-3/template/README.md
- Update README.md files for the repo and each individual template
- Minor fixes to the DEVELOPERS.md file
> Update documentation files

- .gitignore
- CHANGELOG.md
- template-base-2/README.md
- template-base-2/package.json
- template-base-2/template/package.dev.json
- template-base-3-typescript/README.md
- template-base-3-typescript/package.json
- template-base-3-typescript/template/package.dev.json
- template-base-3/README.md
- template-base-3/package.json
- template-base-3/template/package.dev.json
- template-sample-app-2/README.md
- template-sample-app-2/package.json
- template-sample-app-2/template/package.dev.json
- template-sample-app-3/README.md
- template-sample-app-3/package.json
- template-sample-app-3/template/package.dev.json
- Public demo app is based on sample-app-3 [#330](https://github.com/CartoDB/carto-react-template/pull/330)
- Bump versions: carto-react 1.2.1 and deck.gl 8.7.0 [#329](https://github.com/CartoDB/carto-react-template/pull/329)
- Fix x axis labels of Histogram widget in template-base-{2,3} [#327](https://github.com/CartoDB/carto-react-template/pull/327)
- Fix widgets in Tileset view for template-sample-app-3 [#325](https://github.com/CartoDB/carto-react-template/pull/325)
- Fix useMapHooks to ignore undefined tooltips [#326](https://github.com/CartoDB/carto-react-template/pull/326)
> Release 1.2.0

- CHANGELOG.md
- template-base-3-typescript/template/src/components/common/map/useMapHooks.tsx
Skip import of @deck.gl in typescript code.
> Fix template-base-3-typescript typescript error

- CHANGELOG.md
- template-base-3-typescript/template/src/components/common/map/useMapHooks.tsx
- template-base-3/template/src/components/common/map/useMapHooks.js
- template-sample-app-3/template/src/components/common/map/useMapHooks.js
> Fix tooltip styles
