template/src/components/common/Isochrone.js, template/src/components/views/datasets/Datasets.js, template/src/components/views/stores/StoresDetail.js, template/src/lib/api/Geocoding.js, template/src/lib/api/SQL.js, template/src/lib/api/UserDatasets.js, template/src/lib/utils/requestsUtils.js, template/src/lib/widgets/CategoryWidget.js, template/src/lib/widgets/FormulaWidget.js, template/src/lib/widgets/HistogramWidget.js, template/src/lib/widgets/models/CategoryModel.js, template/src/lib/widgets/models/FormulaModel.js, template/src/lib/widgets/models/HistogramModel.js, template/src/models/IsochroneModel.js, template/src/models/StoreModel.js
Add cancelable mechanism to SQL api / datasets fetch requests + its application to:
Allow the use of signal & AbortController to abort fetch requests, so they are correctly cleaned up in react components, and they don't throw errors on console like this one:
This adds cleanup functions to each component.
=> Add cancelable SQL api requests

template/src/components/views/Kpi.js, template/src/components/views/stores/StoresDetail.js, template/src/components/views/stores/StoresList.js, template/src/lib/widgets/CategoryWidget.js, template/src/lib/widgets/FormulaWidget.js, template/src/lib/widgets/HistogramWidget.js
This allows decoupling widgets from setError (currently in the app), so it is required to split the lib
=> Manage errors from views, using onError in widgets

template/src/lib/basemaps/GoogleMap.js, template/src/lib/basemaps/GoogleMap.module.css
Allows specifying width, height and a general 'style' prop, as the DeckGL react component does, including good defaults internally. (The approach is inspired by same props on DeckGL react component).
This allows moving the GoogleMap component to a external lib, without dealing with external css
=> feat: add configuration options for GoogleMap component

CHANGELOG.md, template-sample-app/template.json, template-sample-app/template/package.dev.json, template-sample-app/template/src/utils/formatter.js, template-skeleton/template.json, template-skeleton/template/package.dev.json, template-skeleton/template/src/utils/formatter.js
Fixes https://github.com/CartoDB/carto-react-template/issues/132
Some properties like `notation` & `compactDisplay` are not supported yet by Safari. To get a better support, we add this polyfill: https://www.npmjs.com/package/@formatjs/intl-numberformat
=> Fix number formatting issues in Safari

CHANGELOG.md, template-sample-app/template/public/logo-xs.svg, template-sample-app/template/src/App.js, template-sample-app/template/src/components/common/Header.js, template-sample-app/template/src/components/views/Main.js, template-sample-app/template/src/components/views/UserMenu.js, template-skeleton/template/public/logo-xs.svg, template-skeleton/template/src/components/common/Header.js, template-skeleton/template/src/components/views/Main.js, template-skeleton/template/src/components/views/UserMenu.js
Related to https://app.clubhouse.io/cartoteam/story/121312/mobile-support-sample-app-and-skeleton
=> Mobile layout

CHANGELOG.md, template-sample-app/template.json, template-sample-app/template/package.dev.json, template-sample-app/template/src/utils/formatter.js, template-skeleton/template.json, template-skeleton/template/package.dev.json, template-skeleton/template/src/utils/formatter.js
Polyfills required to support NumberFormat in ios v13
Related to #133
=> Fix ios13 issues on number format use

CHANGELOG.md, template-sample-app/template.json, template-sample-app/template/package.dev.json, template-sample-app/template/public/index.html, template-sample-app/template/src/App.js, template-sample-app/template/src/components/common/Header.js, template-sample-app/template/src/components/legends/Legend.js, template-sample-app/template/src/components/views/Kpi.js, template-sample-app/template/src/components/views/Main.js, template-sample-app/template/src/components/views/UserMenu.js, template-sample-app/template/src/components/views/datasets/Datasets.js, template-sample-app/template/src/components/views/datasets/UserDatasets.js, template-sample-app/template/src/components/views/stores/StoresDetail.js, template-sample-app/template/src/components/views/stores/StoresList.js, template-sample-app/template/src/config/appSlice.js, template-sample-app/template/src/utils/formatter.js, template-skeleton/template.json, template-skeleton/template/package.dev.json, template-skeleton/template/public/index.html, template-skeleton/template/src/App.js, template-skeleton/template/src/components/common/Header.js, template-skeleton/template/src/components/views/Main.js, template-skeleton/template/src/components/views/UserMenu.js, template-skeleton/template/src/config/appSlice.js, template-skeleton/template/src/utils/formatter.js
Story details: https://app.clubhouse.io/cartoteam/story/122791
=> QA mobile - CARTO for React

template-sample-app/template/src/App.js, template-sample-app/template/src/components/views/login/Login.js, template-sample-app/template/src/config/appSlice.js, template-skeleton/template/src/App.js, template-skeleton/template/src/components/views/login/Login.js, template-skeleton/template/src/config/appSlice.js
`forceOAuthLogin`: if configured via appSlice, a new fullscreen Login protects the whole app
This is compatible with the (current) presence of a UserMenu, to Logout or Go to Dashboard.
=> Add a new forceOAuthLogin option to appSlice

CHANGELOG.md, template-sample-app/template/src/App.js, template-sample-app/template/src/components/layers/OAuthLayer.js, template-sample-app/template/src/components/views/datasets/UserDatasets.js, template-sample-app/template/src/components/views/login/Login.js, template-sample-app/template/src/components/views/stores/StoresDetail.js, template-sample-app/template/src/config/appSlice.js, template-sample-app/template/src/config/initialStateSlice.js, template-skeleton/template/src/App.js, template-skeleton/template/src/components/views/login/Login.js, template-skeleton/template/src/config/appSlice.js
TO BE MERGED AFTER: #146 
Use again datasets read all scope, with better performance. This is a simplified approach, without requiring an extra OAuth request per each dataset.
It requires first https://github.com/CartoDB/carto-react-lib/pull/45/ to fix an issue with removeLayer (and change of icon in the datasets list)
=>  feat: adapt UserDatasets to datasets read-all scope

template-sample-app/template/src/components/layers/StoresLayer.js, template-sample-app/template/src/components/legends/Legend.js, template-sample-app/template/src/components/views/Main.js, template-skeleton/template/src/components/views/Main.js
Related to https://app.clubhouse.io/cartoteam/story/122791/qa-mobile-functionality-carto-for-react
=> Mobile fixes

CHANGELOG.md, template-sample-app/template/src/components/views/datasets/UserDatasets.js
Small change after https://github.com/CartoDB/carto-react-lib/pull/52
The final decision is to be homogeneous on `layerAttributes` param behaviour, for both `addLayer` and `updateLayer` actions, reading the params directly from the layer
=> fix: use of layerAttributes in UserDatasets

CHANGELOG.md, template-sample-app/package.json, template-sample-app/template.json, template-sample-app/template/package.dev.json, template-skeleton/package.json, template-skeleton/template.json, template-skeleton/template/package.dev.json
Related to https://github.com/CartoDB/carto-react-template/issues/160
Some dependencies are not detected using cra by an end user, during yarn start (from node14 LTS). Those are added here to dependencies, as no devDependencies are allowed in the template.json file for a template.
This will be treated as a hot-fix release.
=> fix: missing babel dependencies

CHANGELOG.md, template-sample-app/template/src/components/views/Main.js, template-skeleton/template/src/components/views/Main.js
Due to the lack of a required ref to the dom element
Related to #162
=> fix: basic tab layout id broken on first load

template-sample-app/template.json, template-sample-app/template/package.dev.json, template-skeleton/template.json, template-skeleton/template/package.dev.json
Update deck.gl version to `8.4.0-beta.2`. `MVTLayer` binary data support included (among other improvements).
=> Update deck.gl to 8.4.0-beta.2

docs/guides/02_page_layer_widgets.md, template-sample-app/template/src/components/views/Tileset.js, template-sample-app/template/src/components/views/stores/StoresList.js
Related with https://github.com/CartoDB/carto-react-lib/pull/75
- Add required `id` prop for `FormulaWidget`.
=> fix: add required id prop in Formula Widget

CHANGELOG.md, template-sample-app/template/src/components/common/Map.js, template-skeleton/template/src/components/common/Map.js
There was a hard interaction on mobile when trying to click on layers, especially point type. Added `pickingRadius` to all layers.
For: https://app.clubhouse.io/cartoteam/story/126895/qa-hard-interactivity-on-mobile
=> fix: hard interactivity on mobile - add pickingRadius to layers

CHANGELOG.md, template-sample-app/template/src/components/layers/GeocoderLayer.js, template-sample-app/template/src/utils/svgToDataUrl.js
Geocoding marker is not showing on Safari.
For: https://app.clubhouse.io/cartoteam/story/132670/qa-safari-geocoding-marker-is-not-showing
=> fix: geocoding marker is not showing on Safari

README.md
@VictorVelarde I'm not sure if this symbol link breaks the generation of the template, since the generation should overwrite the _templates symbol link by the actual folder
=> Fix instructions for templates

CHANGELOG.md, hygen/_templates/layer/new/layer.ejs.t, template-sample-app/template/src/components/layers/KpiLayer.js, template-sample-app/template/src/components/layers/StoresLayer.js, template-sample-app/template/src/components/layers/TilesetLayer.js, template-sample-app/template/src/utils/htmlForFeature.js
Improve default popup with `htmlForFeature` fn.
`htmlForFeature` function now accepts the following parameters as the first argument:
```javascript
title: `String` // popup title, by default comes with a `strong` and `h3` html tags
feature: `{}` // needs `info.object` from deck.gk
formatter: {
type: `'currency'` | `'number'`,
columns: `[]` // feature columns to apply the formatter type
}
includeColumns: `[String] | '*'` // include in the popup all fields using '*' or some using `['cartodb_id', 'test']`
showColumnName: `boolean` // whether or not to show the column name as a prefix of the row
```
Example:
```javascript
onHover: (info) => {
if (info?.object) {
info.object = {
html: htmlForFeature({
title: `${info.object.properties.name}`,
feature: info.object,
formatter: {
type: 'currency', …
```
=> feat: improve default popup with htmlForFeature

CHANGELOG.md, hygen/_templates/layer/new/prompt.js, hygen/_templates/source/new/prompt.js, hygen/_templates/source/new/source.ejs.t, template-sample-app/template/src/components/layers/KpiLayer.js, template-sample-app/template/src/components/layers/StoresLayer.js, template-sample-app/template/src/data/sources/tilesetSource.js, template-sample-app/template/src/utils/htmlForFeature.js
Rename BigQuery source type, from `bq` to `bigquery`
For: https://app.clubhouse.io/cartoteam/story/135148/rename-source-type-in-template
Related with: https://github.com/CartoDB/carto-react-lib/pull/97
=> refactor: rename bigquery source type

CHANGELOG.md, template-sample-app/template/src/utils/formatter.js, template-skeleton/template/src/utils/formatter.js
For some reason I had issues with recovering locally the branch at https://github.com/CartoDB/carto-react-template/pull/208/files, so I'm just applying Dani's work here
=> Fix bug in formatter applied to histogram

CHANGELOG.md, template-skeleton/template/src/store/store.js
For: https://app.clubhouse.io/cartoteam/story/141680/redux-store-config-not-updated-in-skeleton
=> fix: update redux middleware in skeleton

CHANGELOG.md, template-skeleton-cn/template/src/App.js, template-skeleton-cn/template/src/Auth0.js, template-skeleton-cn/template/src/index.js, template-skeleton-cn/template/src/routes.js
It allows to create public apps with cloud native.
If the `oauth`is missing in the initialSlice the app is public and no login form will appear.
How it works:
1. Create a public token from the tokens api
2. Remove the oauth property from initialSlice.
3. Add the token at initialSlice.
```javascript
import { VOYAGER } from '@carto/react-basemaps';
import { API_VERSIONS } from '@deck.gl/carto';
export const initialState = {
...
credentials: {
apiVersion: API_VERSIONS.V3,
apiBaseUrl: 'https://gcp-us-east1.api.carto.com',
accessToken:
'XXX',
},
};
```
=> Create public apps with cloud native

template-skeleton/template/src/App.js, template-skeleton/template/src/components/common/Header.js, template-skeleton/template/src/components/common/Map.js, template-skeleton/template/src/components/common/ZoomControl.js, template-skeleton/template/src/components/views/NotFound.js, template-skeleton/template/src/components/views/login/Login.js
This PR improve the default classes name of component, The main objetive is to facilitate the debugging of the layout and to be able to see better where each component is in the DOM tree.
Before:
After:
You can see now the makeStyles-<COMPONENT_NAME> instead of makeStyles-root.
=> Improve default classes name

CHANGELOG.md, template-sample-app/template/src/components/views/stores/StoresList.js, template-sample-app/template/src/data/sources/storesSource.js
Thanks to the new widget, available at carto-react lib from 1.1.0-alpha.3
=> Add a ScatterplotWidget example to sample-app

template-base-3-typescript/template/gitignore, template-sample-app-3/template/gitignore
Story details: https://app.shortcut.com/cartoteam/story/188818
=> Fix config-overrides.js being ignored in base-3-typescript & sample-app-3

CHANGELOG.md, template-base-2/template/src/components/common/map/useMapHooks.js, template-base-3/template/src/components/common/map/useMapHooks.js, template-sample-app-2/template/src/components/common/map/useMapHooks.js
Story details:  https://app.shortcut.com/cartoteam/story/211280/template-base-2-feature-selection-widget-with-undefined-label
=> Fix useMapHooks to ignore undefined tooltips.

CHANGELOG.md, template-base-2/template/src/utils/formatter.js, template-base-3/template/src/utils/formatter.js
Use proper `parseLogicalOperation` from `sample-app-3`.
Fixes
* https://app.shortcut.com/cartoteam/story/211256/template-base-2-the-x-axis-labels-has-a-wrong-value-in-the-histogram-widget
* https://app.shortcut.com/cartoteam/story/210538/template-base-3-the-x-axis-labels-has-a-wrong-value-in-the-histogram-widget
=> Fix x axis labels of Histogram widget in template-base-{2,3}

template-sample-app-3/template/src/components/views/Stores.js, template-sample-app-3/template/src/components/views/Tileset.js
Stores view:
Changes:
- Remove ticks in HistogramWidget
- Use BarWidget for storetype
- Add CategoryWidget for states
- Add global formula widget with the sum of revenues to compare with the viewport one
Tileset view:
Changes:
- Remove ticks in HistogramWidget.
=> Prepare template-sample-app-3 for 1.3.0

CHANGELOG.md, template-sample-app-3/template/src/components/layers/StoresLayer.js
The CartoLayer only works with dynamic tiles so feature dropping can happen at lower zoom levels. If feature dropping happens, the widgets linked to the same source are not going to work. If we want the widgets to work at all zoom levels, we need to fetch the data in GeoJSON format and then use the GeoJsonLayer intead of the CartoLayer.
=> Use the GeoJsonLayer instead of the CartoLayer in sample-app-3 template

CHANGELOG.md, template-base-3-typescript/package.json, template-base-3-typescript/template/package.dev.json, template-base-3/package.json, template-base-3/template/package.dev.json, template-sample-app-3/package.json, template-sample-app-3/template/package.dev.json
Register proper 2.2.0 for tagging purposes
=> Update to 2.2 (published)
